[[apps]]
name = "Kodi"
exec = "kodi"
icon = ""
category = "Media"

[[apps]]
name = "Plex"
exec = "plex-media-player"
icon = ""
category = "Media"

[[apps]]
name = "YouTube"
exec = "chromium --app=https://www.youtube.com/tv"
icon = ""
category = "Media"

[[apps]]
name = "Firefox"
exec = "firefox"
icon = ""
category = "Web"

[[apps]]
name = "Files"
exec = "dolphin"
icon = ""
category = "Utilities"
